title: Gallery
description: description is here
theme: jekyll-theme-dinky
baseurl: "/v_test"
show_downloads: false
is_project_page: false
is_user_page: false

collections:
  videos:
    output: true
    permalink: /videos/:name/
