title: MP4 Video Gallery
description: GitHub Pages
theme: jekyll-theme-dinky # minima
baseurl: "/v_test"
collections:
  videos:
    output: true
    permalink: /videos/:name/

# custom navi menu
nav_links:
  Home: "/v_test"
