title: MP4 Video Gallery
description: GitHub Pages
theme: jekyll-theme-dinky # minima
baseurl: "/v_test"
show_downloads: false

collections:
  videos:
    output: true
    permalink: /videos/:name/


